### ISSUE TITLE
unband

### ISSUE THREAD

**Issue by harrypotter06** [nachmore/unBand#43] opened 2015-02-26 00:18 UTC
Hello, 

the App Crash. You wrote: "To solve this, copy Microsoft.Cargo.Client.Desktop8.dll from wherever it is installed to c:\Program Files(x86)\Microsoft Band Sync." - but on my PC isn't this DLL .....

**Comment by nachmore** [comment] 2015-02-27 05:23
Dupe of #41

**Closed by nachmore** 2015-02-27 05:23 UTC
