### ISSUE TITLE
Crash on startup. Windows 10 Yoga 1 Pro

### ISSUE THREAD

**Issue by bc3tech** [nachmore/unBand#22] opened 2015-01-14 17:50 UTC
Text from messagebox:

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Cargo.Client.Desktop8, Version=1.3.1106.2, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.

File name: 'Microsoft.Cargo.Client.Desktop8, Version=1.3.1106.2, Culture=neutral, PublicKeyToken=null'

   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)

   at System.Reflection.RuntimePropertyInfo.get_Signature()

   at System.Reflection.RuntimePropertyInfo.get_PropertyType()

   at MS.Internal.Data.PropertyPathWorker.GetInfo(Int32 k, Object item, SourceValueState& svs)

   at MS.Internal.Data.PropertyPathWorker.ReplaceItem(Int32 k, Object newO, Object parent)

   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)

   at MS.Internal.Data.ClrBindingWorker.AttachDataItem()

   at System.Windows.Data.BindingExpression.Activate(Object item)

   at System.Windows.Data.BindingExpression.AttachToContext(AttachAttempt attempt)

   at System.Windows.Data.BindingExpression.MS.Internal.Data.IDataBindEngineClient.AttachToContext(Boolean lastChance)

   at MS.Internal.Data.DataBindEngine.Task.Run(Boolean lastChance)

   at MS.Internal.Data.DataBindEngine.Run(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.

To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.

Note: There is some performance penalty associated with assembly bind failure logging.

To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

---------------------------
OK   
---------------------------

**Comment by nachmore** [comment] 2015-01-14 18:08
Thanks for the crash report - this is unrelated to Windows 10. Do you have the Band Sync app installed and if so, what is the path to it?

**Comment by bc3tech** [comment] 2015-01-14 19:42
I do in fact have it installed.

Path to it, found by following the shortcuts from the start menu, is
`C:\Program Files (x86)\Microsoft Band Sync`

**Comment by nachmore** [comment] 2015-01-15 09:20
I've found the best path to pull the dll from, I'm going to get this in over the next day or so and I'll push a version with this in the next few days.

For now though, marking this as a duplicate of #9. Thanks for the report!

**Closed by nachmore** 2015-01-15 09:20 UTC
