### ISSUE TITLE
Crash due to Exception: name cannot have length 0

### ISSUE THREAD

**Issue by bdubz06** [nachmore/unBand#49] opened 2015-02-28 01:25 UTC
Please help!

---------------------------
Imminent Crash
---------------------------
An unhandled exception occurred - sorry about that, we're going to have to crash now :(

You can open a bug with a copy of this crash: hit Ctrl + C right now and then paste into a new bug at https://github.com/nachmore/unBand/issues.

System.ArgumentException: name cannot have length 0.

   at Microsoft.Band.Admin.CargoStrapp.SetName(Guid id, String name)

   at Microsoft.Band.Admin.CargoStrapp..ctor(Guid id, String name, StrappSettings strappSettings, IList`1 images, UInt32 tileImageIndex, IList`1 layouts, Nullable`1 badgeImageIndex)

   at Microsoft.Band.Admin.TileDataExtensions.ToCargoStrapp(TileData data, TileIconRleData icon)

   at Microsoft.Band.Admin.CargoClient.StrappStructToClass(List`1 list)

   at Microsoft.Band.Admin.CargoClient.GetStartStrip()

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>b__251()

   at System.Threading.Tasks.Task`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Band.Admin.CargoClient.<GetStartStripAsync>d__252.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandTiles.<InitAsync>d__1.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at unBand.BandHelpers.BandManager.<>c__DisplayClassb.<<ConnectDevice>b__9>d__d.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by nachmore** [comment] 2015-03-01 03:20
dupe of #46 - see comments in that bug for a suggested fix.

**Closed by nachmore** 2015-03-01 03:20 UTC
